apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-openshift
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-openshift
    app.kubernetes.io/part-of: hello-openshift
  name: hello-openshift
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hello-openshift
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hello-openshift
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdavis-se-jboss-tenant/hello-openshift/hello-openshift@sha256:1af8d6f339b564f2794849cef315989a40e09891b4a668df2af13fa473521345
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
